### PR TITLE
README.md: update README to link it from lava-docs

### PR DESCRIPTION
**Pull request by jroimartin**
This PR updates the README file to link it from `lava-docs`.

### CODE REVIEW

**Review by jesusfcr — APPROVED** [review]
LGTM

**Review by jesusfcr — COMMENTED** [review]
I don't think this is an optimal solution as it makes imposible for the user to get instructions about how lava-action works in other than the last one (or the one in lava-docs as lava-docs doesn't allow to get info from different versions).

Also it makes the process of updating an action spread in two repositories (two PR), because the update of the lava-docs is not automated.

**Review by seilagamo — APPROVED** [review]
LGTM

**Comment by jroimartin** [comment]
> I don't think this is an optimal solution as it makes imposible for the user to get instructions about how lava-action works in other than the last one (or the one in lava-docs as lava-docs doesn't allow to get info from different versions).
> 
> Also it makes the process of updating an action spread in two repositories (two PR), because the update of the lava-docs is not automated.

Very good points. I modified this PR to just update the README file so it can be linked from lava-docs. This repository will continue being the single point of truth for the lava-action documentation.

**Review by jesusfcr — APPROVED** [review]
LGTM

**Pull request merged**
